language: generic
sudo : required
services:
  - docker

before_install:
  - docker build -t squaresdev/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true squaresdev/react-test npm test -- --coverage

after_success:
  - docker build -t squaresdev/multi-client ./client
  - docker build -t squaresdev/multi-nginx ./nginx
  - docker build -t squaresdev/multi-server ./server
  - docker build -t squaresdev/multi-worker ./worker

  # now to log into Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take the images and push them to docker hub
  - docker push squaresdev/multi-client
  - docker push squaresdev/multi-nginx 
  - docker push squaresdev/multi-server
  - docker push squaresdev/multi-worker
