language: generic
sudo : required
services:
  - docker

before_install:
  -docker build -t squaresdev/react-test -f ./client/Dockerfile ./client

script:
  - docker run -e CI=true squaresdev/react-test npm test -- --coverage

after_success:
  - docker build -t squaresdev/multi-client ./client
  - docker build -t squaresdev/multi-nginx ./nginx
  - docker build -t squaresdev/multi-server ./server
  - docker build -t squaresdev/multi-nworker./worker
